#!/bin/bash

. developers.list
. mailmap2019

header="#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by script
#

"

cd list
f=`find . -name "gitlog*$1.list"`

for fp in $f ; do
  unset list
  declare -A list
  
  lang=$fp
  lang=${lang#*_}
  lang=${lang%.list}
  outfp=${fp/gitlog/translators}
  outfp=${outfp%list}info
  fp2019="../"${outfp/translators/translators2019/translators}

  if [[ -e $fp2019 ]] ; then
    echo $fp2019
    IFS=$'\n'
    lines=`cat $fp2019`
    author=""
    for line in $lines; do
      unset IFS
      case $line in
        translator_*_nameEnglish*)
          if [[ "$author" != "" ]] ; then
            let list["${map2019[$author]:-$author}"]=0
          fi
          author=${line#*= }
          author=${author% }
          ;;
        translator_*_contact*)
          mail=${line#*= }
          mail=${mail// /+}
          mail=${mail//[<>]/}
          author="$author $mail"
          ;;
      esac
    done
    if [[ "$author" != "" ]] ; then
      let list["${map2019[$author]:-$author}"]=0
    fi
  fi

  echo -n "$outfp "
  IFS=$'\n'
  lines=`cat $fp`
  for line in $lines; do
    unset IFS
    case ${line:0:1} in
      "F")
        filename=${line#??}
        echo -n "."
        ;;
      "A")
        author=${line#??}
        dev=false
        let count=0
        for a in ${developers[${author##* }]} ; do
          dev=true
          if [[ $a == $lang ]] ; then
            dev=false
            break
          fi
        done
        ;;
      " ")
        if ! $dev && (( $count > 0 )) ; then
          let list["$author"]=list["$author"]+count
        fi
        ;;
      [0-9])
        if [[ $line =~ .*/[^_]*_(.*).ts ]] ; then
          la1=${BASH_REMATCH[1]}
          la2=$lang
          if [[ ${la1:0:2} != ${la2:0:2} ]] ; then
            dev=true
          fi
        elif ! [[ $line =~ .*(.desktop.in|.desktop|.ts) ]] ; then
          dev=true
        fi
        if [[ $line =~ .*$filename ]] ; then
          let count=count+${line%%$'\t'*}
        fi
        ;;
    esac
  done
  
  unset IFS
  all=$(
    for author in "${!list[@]}"; do
      echo ${list[$author]} $author
    done | sort -k2 -f  # sort by Author
    #done | sort -nr     # sort by Count
  )
  
  IFS=$'\n'
  num=1
  oneline="#[Lang] Lines <Mail> Name"$'\n'
  info=""
  for line in $all; do
    count=${line%% *}
    author=${line#* }
    author=${author% *}
    mail=${line##* }
    if [[ ${mail#*@} == "users.noreply.github.com" ]]; then
      mail=${mail%@*}
      mail=https://github.com/${mail#*+}
    fi
    printf -v str "%5d %-40s" $count "<$mail>"
    oneline=$oneline"#[$lang] $str $author"$'\n'
    info=$info$'\n'"translator_${num}_nameEnglish = $author"
    if [[ "$mail" != "@" ]] ; then
      info=$info$'\n'"translator_${num}_contact = $mail"
    fi
    info=$info$'\n'
    let num++
  done
  if [[ "$info" == "" ]] ; then
    echo -n "R"
    rm -f $outfp
  else
    echo "$header$oneline$info" > $outfp
  fi
  echo
done
