name: Create translators pull request action
on:
  schedule:
    - cron: "0 21 * * *"
  repository_dispatch:
    types: [translators-action]
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - run: "cd translators && ./make_list_clone.sh"
      - run: "cd translators && ./make_list_mailmap.sh"
      - run: "cd translators && ./make_list_gitlog.sh"
      - run: "cd translators && ./make_list_info.sh"
      - run: "cd translators && ./copy_info.sh"
      - run: "cd translators && ./clean_list.sh"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Created translators info from GitHub action"
          title: "Update translators info from GitHub action"
          body: "Create new translators_*.info"
          branch: translators-action
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
