name: Create translators pull request action
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - run: "cd translators && ./make_list_clone.sh"
      - run: "cd translators && ./make_list_mailmap.sh"
      - run: "cd translators && ./make_list_gitlog.sh"
      - run: "cd translators && ./make_list_info.sh"
      - run: "cd translators && ./copy_info.sh"
      - run: "cd translators && ./clean_list.sh"
      - uses: gr2m/create-or-update-pull-request-action@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Update translators from Github action"
          body: ""
          branch: "translators-action"
          commit-message: "Updated translators info from Github action"
          author: Action-bot <create-or-update-pull-request@users.noreply.github.com>
